"""Curated, source-grounded authoring helpers for forecast methods v001.

This module is deliberately declarative: it records reviewed primary sources and
the evidence assignment for each migrated method.  It does not infer provenance
from names and it drops legacy constructs for which no reviewed definition was
found.
"""
from __future__ import annotations

import json
from pathlib import Path
from typing import Mapping, Sequence

from .contracts import MethodCard, SourceRecord
from .seed import CATEGORY_BY_LEGACY_ID


SOURCE_PAYLOADS: tuple[Mapping[str, object], ...] = (
    {
        "source_id": "source_000001",
        "title": "Forecasting: Principles and Practice (3rd ed)",
        "authors": ["Rob J. Hyndman", "George Athanasopoulos"],
        "year": 2021,
        "source_type": "textbook",
        "url": "https://otexts.com/fpp3/",
        "doi": "",
        "isbn": "9780987507136",
        "retrieved_at": "2026-08-17",
        "primary": True,
        "review_status": "verified",
    },
    {
        "source_id": "source_000002",
        "title": "StatsForecast model documentation",
        "authors": ["Nixtla"],
        "year": 2026,
        "source_type": "official_docs",
        "url": "https://nixtlaverse.nixtla.io/statsforecast/src/core/models.html",
        "doi": "",
        "isbn": "",
        "retrieved_at": "2026-08-17",
        "primary": True,
        "review_status": "verified",
    },
    {
        "source_id": "source_000003",
        "title": "Statsmodels state space methods documentation",
        "authors": ["Statsmodels developers"],
        "year": 2026,
        "source_type": "official_docs",
        "url": "https://www.statsmodels.org/stable/statespace.html",
        "doi": "",
        "isbn": "",
        "retrieved_at": "2026-08-17",
        "primary": True,
        "review_status": "verified",
    },
    {
        "source_id": "source_000004",
        "title": "The theta model: a decomposition approach to forecasting",
        "authors": ["Vassilis Assimakopoulos", "Konstantinos Nikolopoulos"],
        "year": 2000,
        "source_type": "paper",
        "url": "https://doi.org/10.1016/S0169-2070(00)00066-2",
        "doi": "10.1016/S0169-2070(00)00066-2",
        "isbn": "",
        "retrieved_at": "2026-08-17",
        "primary": True,
        "review_status": "verified",
    },
    {
        "source_id": "source_000005",
        "title": "Forecasting and stock control for intermittent demands",
        "authors": ["J. D. Croston"],
        "year": 1972,
        "source_type": "paper",
        "url": "https://doi.org/10.1057/jors.1972.50",
        "doi": "10.1057/jors.1972.50",
        "isbn": "",
        "retrieved_at": "2026-08-17",
        "primary": True,
        "review_status": "verified",
    },
    {
        "source_id": "source_000006",
        "title": "The accuracy of intermittent demand estimates",
        "authors": ["John E. Boylan", "Aris A. Syntetos"],
        "year": 2005,
        "source_type": "paper",
        "url": "https://doi.org/10.1016/j.ijforecast.2004.10.001",
        "doi": "10.1016/j.ijforecast.2004.10.001",
        "isbn": "",
        "retrieved_at": "2026-08-17",
        "primary": True,
        "review_status": "verified",
    },
    {
        "source_id": "source_000007",
        "title": "Intermittent demand: linking forecasting to inventory obsolescence",
        "authors": ["Ruud H. Teunter", "Aris A. Syntetos", "M. Zied Babai"],
        "year": 2011,
        "source_type": "paper",
        "url": "https://doi.org/10.1016/j.ejor.2010.09.018",
        "doi": "10.1016/j.ejor.2010.09.018",
        "isbn": "",
        "retrieved_at": "2026-08-17",
        "primary": True,
        "review_status": "verified",
    },
    {
        "source_id": "source_000008",
        "title": "An aggregate-disaggregate intermittent demand approach",
        "authors": [
            "Konstantinos Nikolopoulos",
            "Aris A. Syntetos",
            "John E. Boylan",
            "Fotios Petropoulos",
            "Vassilis Assimakopoulos",
        ],
        "year": 2011,
        "source_type": "paper",
        "url": "https://doi.org/10.1016/j.ijforecast.2010.09.008",
        "doi": "10.1016/j.ijforecast.2010.09.008",
        "isbn": "",
        "retrieved_at": "2026-08-17",
        "primary": True,
        "review_status": "verified",
    },
    {
        "source_id": "source_000009",
        "title": "Improving forecasting by estimating time series structural components across multiple frequencies",
        "authors": ["Nikolaos Kourentzes", "Fotios Petropoulos", "Juan R. Trapero"],
        "year": 2014,
        "source_type": "paper",
        "url": "https://doi.org/10.1016/j.ijforecast.2013.09.006",
        "doi": "10.1016/j.ijforecast.2013.09.006",
        "isbn": "",
        "retrieved_at": "2026-08-17",
        "primary": True,
        "review_status": "verified",
    },
    {
        "source_id": "source_000010",
        "title": "STL: A seasonal-trend decomposition procedure based on loess",
        "authors": ["Robert B. Cleveland", "William S. Cleveland", "Jean E. McRae", "Irma Terpenning"],
        "year": 1990,
        "source_type": "paper",
        "url": "https://www.wessa.net/download/stl.pdf",
        "doi": "",
        "isbn": "",
        "retrieved_at": "2026-08-17",
        "primary": True,
        "review_status": "verified",
    },
    {
        "source_id": "source_000011",
        "title": "Forecast combinations: an over 50-year review",
        "authors": ["Xiaoqian Wang", "Rob J. Hyndman", "Feng Li", "Yanfei Kang"],
        "year": 2023,
        "source_type": "paper",
        "url": "https://robjhyndman.com/publications/combinations/",
        "doi": "",
        "isbn": "",
        "retrieved_at": "2026-08-17",
        "primary": True,
        "review_status": "verified",
    },
    {
        "source_id": "source_000012",
        "title": "Forecasting at scale",
        "authors": ["Sean J. Taylor", "Benjamin Letham"],
        "year": 2018,
        "source_type": "paper",
        "url": "https://doi.org/10.1080/00031305.2017.1380080",
        "doi": "10.1080/00031305.2017.1380080",
        "isbn": "",
        "retrieved_at": "2026-08-17",
        "primary": True,
        "review_status": "verified",
    },
)

ADDITIONAL_STATISTICAL_SOURCE_PAYLOADS: tuple[Mapping[str, object], ...] = (
    {
        "source_id": "source_000013",
        "title": "Predicting chaotic time series",
        "authors": ["J. Doyne Farmer", "John J. Sidorowich"],
        "year": 1987,
        "source_type": "paper",
        "url": "https://doi.org/10.1103/PhysRevLett.59.845",
        "doi": "10.1103/PhysRevLett.59.845",
        "isbn": "",
        "retrieved_at": "2026-08-17",
        "primary": True,
        "review_status": "verified",
    },
    {
        "source_id": "source_000014",
        "title": "Conformal prediction interval for dynamic time-series",
        "authors": ["Chen Xu", "Yao Xie"],
        "year": 2021,
        "source_type": "paper",
        "url": "https://proceedings.mlr.press/v139/xu21h.html",
        "doi": "",
        "isbn": "",
        "retrieved_at": "2026-08-17",
        "primary": True,
        "review_status": "verified",
    },
    {
        "source_id": "source_000015",
        "title": "Gaussian Processes for Machine Learning",
        "authors": ["Carl Edward Rasmussen", "Christopher K. I. Williams"],
        "year": 2006,
        "source_type": "textbook",
        "url": "https://gaussianprocess.org/gpml/",
        "doi": "",
        "isbn": "9780262182539",
        "retrieved_at": "2026-08-17",
        "primary": True,
        "review_status": "verified",
    },
    {
        "source_id": "source_000016",
        "title": "MLForecast documentation",
        "authors": ["Nixtla"],
        "year": 2026,
        "source_type": "official_docs",
        "url": "https://nixtlaverse.nixtla.io/mlforecast/",
        "doi": "",
        "isbn": "",
        "retrieved_at": "2026-08-17",
        "primary": True,
        "review_status": "verified",
    },
    {
        "source_id": "source_000017",
        "title": "DeepAR: Probabilistic forecasting with autoregressive recurrent networks",
        "authors": ["David Salinas", "Valentin Flunkert", "Jan Gasthaus"],
        "year": 2017,
        "source_type": "paper",
        "url": "https://arxiv.org/abs/1704.04110",
        "doi": "",
        "isbn": "",
        "retrieved_at": "2026-08-17",
        "primary": True,
        "review_status": "verified",
    },
    {
        "source_id": "source_000018",
        "title": "N-BEATS: Neural basis expansion analysis for interpretable time series forecasting",
        "authors": ["Boris N. Oreshkin", "Dmitri Carpov", "Nicolas Chapados", "Yoshua Bengio"],
        "year": 2019,
        "source_type": "paper",
        "url": "https://arxiv.org/abs/1905.10437",
        "doi": "",
        "isbn": "",
        "retrieved_at": "2026-08-17",
        "primary": True,
        "review_status": "verified",
    },
    {
        "source_id": "source_000019",
        "title": "N-HiTS: Neural hierarchical interpolation for time series forecasting",
        "authors": ["Cristian Challu", "Kin G. Olivares", "Boris N. Oreshkin", "Federico Garza", "Max Mergenthaler-Canseco", "Artur Dubrawski"],
        "year": 2022,
        "source_type": "paper",
        "url": "https://arxiv.org/abs/2201.12886",
        "doi": "",
        "isbn": "",
        "retrieved_at": "2026-08-17",
        "primary": True,
        "review_status": "verified",
    },
    {
        "source_id": "source_000020",
        "title": "Temporal Fusion Transformers for interpretable multi-horizon time series forecasting",
        "authors": ["Bryan Lim", "Sercan O. Arik", "Nicolas Loeff", "Tomas Pfister"],
        "year": 2019,
        "source_type": "paper",
        "url": "https://arxiv.org/abs/1912.09363",
        "doi": "",
        "isbn": "",
        "retrieved_at": "2026-08-17",
        "primary": True,
        "review_status": "verified",
    },
    {
        "source_id": "source_000021",
        "title": "Joint estimation of model parameters and outlier effects in time series",
        "authors": ["Chung Chen", "Lon-Mu Liu"],
        "year": 1993,
        "source_type": "paper",
        "url": "https://doi.org/10.1080/01621459.1993.10476344",
        "doi": "10.1080/01621459.1993.10476344",
        "isbn": "",
        "retrieved_at": "2026-08-17",
        "primary": True,
        "review_status": "verified",
    },
    {
        "source_id": "source_000022",
        "title": "A new approach to the economic analysis of nonstationary time series and the business cycle",
        "authors": ["James D. Hamilton"],
        "year": 1989,
        "source_type": "paper",
        "url": "https://doi.org/10.2307/1912559",
        "doi": "10.2307/1912559",
        "isbn": "",
        "retrieved_at": "2026-08-17",
        "primary": True,
        "review_status": "verified",
    },
    {
        "source_id": "source_000023",
        "title": "Threshold Models in Non-linear Time Series Analysis",
        "authors": ["Howell Tong"],
        "year": 1983,
        "source_type": "textbook",
        "url": "https://link.springer.com/book/10.1007/978-1-4684-7888-4",
        "doi": "10.1007/978-1-4684-7888-4",
        "isbn": "9781468478907",
        "retrieved_at": "2026-08-17",
        "primary": True,
        "review_status": "verified",
    },
    {
        "source_id": "source_000024",
        "title": "Specification, estimation, and evaluation of smooth transition autoregressive models",
        "authors": ["Timo Terasvirta"],
        "year": 1994,
        "source_type": "paper",
        "url": "https://doi.org/10.1080/01621459.1994.10476462",
        "doi": "10.1080/01621459.1994.10476462",
        "isbn": "",
        "retrieved_at": "2026-08-17",
        "primary": True,
        "review_status": "verified",
    },
    {
        "source_id": "source_000025",
        "title": "Forecasting time series with complex seasonal patterns using exponential smoothing",
        "authors": ["Alysha M. De Livera", "Rob J. Hyndman", "Ralph D. Snyder"],
        "year": 2011,
        "source_type": "paper",
        "url": "https://doi.org/10.1198/jasa.2011.tm09771",
        "doi": "10.1198/jasa.2011.tm09771",
        "isbn": "",
        "retrieved_at": "2026-08-17",
        "primary": True,
        "review_status": "verified",
    },
    {
        "source_id": "source_000026",
        "title": "Random forests",
        "authors": ["Leo Breiman"],
        "year": 2001,
        "source_type": "paper",
        "url": "https://doi.org/10.1023/A:1010933404324",
        "doi": "10.1023/A:1010933404324",
        "isbn": "",
        "retrieved_at": "2026-08-17",
        "primary": True,
        "review_status": "verified",
    },
    {
        "source_id": "source_000027",
        "title": "XGBoost: A scalable tree boosting system",
        "authors": ["Tianqi Chen", "Carlos Guestrin"],
        "year": 2016,
        "source_type": "paper",
        "url": "https://arxiv.org/abs/1603.02754",
        "doi": "",
        "isbn": "",
        "retrieved_at": "2026-08-17",
        "primary": True,
        "review_status": "verified",
    },
    {
        "source_id": "source_000028",
        "title": "LightGBM: A highly efficient gradient boosting decision tree",
        "authors": ["Guolin Ke", "Qi Meng", "Thomas Finley", "Taifeng Wang", "Wei Chen", "Weidong Ma", "Qiwei Ye", "Tie-Yan Liu"],
        "year": 2017,
        "source_type": "paper",
        "url": "https://proceedings.neurips.cc/paper/2017/hash/6449f44a102fde848669bdd9eb6b76fa-Abstract.html",
        "doi": "",
        "isbn": "",
        "retrieved_at": "2026-08-17",
        "primary": True,
        "review_status": "verified",
    },
    {
        "source_id": "source_000029",
        "title": "A tutorial on support vector regression",
        "authors": ["Alex J. Smola", "Bernhard Scholkopf"],
        "year": 2004,
        "source_type": "paper",
        "url": "https://doi.org/10.1023/B:STCO.0000035301.49549.88",
        "doi": "10.1023/B:STCO.0000035301.49549.88",
        "isbn": "",
        "retrieved_at": "2026-08-17",
        "primary": True,
        "review_status": "verified",
    },
)


EXCLUDED_LEGACY_IDS = {
    "fft_dominant_frequency_extrapolation",
    "wavelet_trend_detail_forecast",
    "empirical_quantile_persistence",
}

SPECIFIC_DEFINITION_SOURCES: Mapping[str, tuple[str, ...]] = {
    "theta_classic": ("source_000004",),
    "theta_optimized": ("source_000002", "source_000004"),
    "croston": ("source_000005",),
    "croston_sba": ("source_000006",),
    "tsb": ("source_000007",),
    "adida": ("source_000008",),
    "imapa": ("source_000009",),
    "local_level_kalman": ("source_000003",),
    "local_linear_trend_kalman": ("source_000003",),
    "structural_time_series_bsm": ("source_000003",),
    "robust_loess_trend": ("source_000010",),
    "piecewise_linear_trend": ("source_000012",),
    "statistical_ensemble_mean": ("source_000011",),
}

EXTRA_STATISTICAL_METHOD_SPECS: tuple[Mapping[str, object], ...] = (
    {
        "name": "nearest_neighbor_lag_analogue",
        "category": "analogue",
        "description": "Match the latest lag vector to historical lag vectors and average their observed continuations.",
        "assumption": "Past states close in lag space have similar future continuations.",
        "failure": "Sparse history or a regime shift leaves no genuinely comparable analogue.",
        "sources": ["source_000013"],
        "hyperparameters": ["lag_length", "neighbor_count", "distance_metric"],
    },
    {
        "name": "dtw_analogue_forecast",
        "category": "analogue",
        "description": "Find historical subsequences with similar shape under dynamic time warping and aggregate their following paths.",
        "assumption": "Shape-similar episodes remain predictive despite local timing distortions.",
        "failure": "A permissive warping window can match unrelated episodes and erase timing information.",
        "sources": ["source_000013", "source_000016"],
        "hyperparameters": ["window_length", "warping_window", "neighbor_count"],
    },
    {
        "name": "split_conformal_residual_intervals",
        "category": "calibration",
        "description": "Calibrate forecast intervals with held-out absolute residual quantiles from a fixed point forecaster.",
        "assumption": "Calibration and forecast residuals are sufficiently exchangeable over the evaluation period.",
        "failure": "Abrupt distribution shifts invalidate residual coverage learned from the calibration window.",
        "sources": ["source_000014"],
        "hyperparameters": ["miscoverage_level", "calibration_window"],
        "probabilistic": True,
    },
    {
        "name": "adaptive_conformal_time_series",
        "category": "calibration",
        "description": "Update conformal interval widths online so recent coverage errors change the next interval.",
        "assumption": "Coverage drift is gradual enough for online score updates to track it.",
        "failure": "Fast alternating regimes cause the adaptation rule to lag or oscillate.",
        "sources": ["source_000014"],
        "hyperparameters": ["miscoverage_level", "adaptation_rate"],
        "probabilistic": True,
    },
    {
        "name": "poisson_dynamic_regression",
        "category": "count_forecasting",
        "description": "Model a count target with a log-linked Poisson mean driven by time and optional predictors.",
        "assumption": "Conditional count variance is close to the conditional mean after included predictors.",
        "failure": "Strong overdispersion, zero inflation, or dependence left in residuals biases uncertainty.",
        "sources": ["source_000001"],
        "hyperparameters": ["lag_features", "regularization"],
        "covariates": True,
        "probabilistic": True,
    },
    {
        "name": "negative_binomial_dynamic_regression",
        "category": "count_forecasting",
        "description": "Forecast overdispersed counts with a dynamic negative-binomial regression mean.",
        "assumption": "A negative-binomial conditional law captures extra-Poisson dispersion.",
        "failure": "Structural zeros or changing dispersion violate the fitted conditional distribution.",
        "sources": ["source_000001"],
        "hyperparameters": ["dispersion", "lag_features"],
        "covariates": True,
        "probabilistic": True,
    },
    {
        "name": "integer_autoregressive_inar",
        "category": "count_forecasting",
        "description": "Use binomial thinning of past integer counts plus an integer-valued innovation process.",
        "assumption": "Count dependence can be represented by stable thinning probabilities and innovations.",
        "failure": "Nonlinear regime changes or strong covariate effects are not represented by a fixed INAR law.",
        "sources": ["source_000001"],
        "hyperparameters": ["order", "innovation_distribution"],
        "probabilistic": True,
    },
    {
        "name": "gaussian_process_autoregression",
        "category": "kernel",
        "description": "Place a Gaussian-process prior over the nonlinear mapping from lag vectors to future values.",
        "assumption": "The chosen kernel expresses the smoothness and similarity structure of the lag-response map.",
        "failure": "Poor kernels extrapolate badly and exact inference scales cubically with training cases.",
        "sources": ["source_000015", "source_000016"],
        "hyperparameters": ["kernel", "lag_length", "noise_level"],
        "probabilistic": True,
    },
    {
        "name": "support_vector_lag_regression",
        "category": "kernel",
        "description": "Fit epsilon-insensitive support-vector regression to lag and calendar features and roll it forward.",
        "assumption": "A fixed kernel can represent the stable nonlinear relationship between features and target.",
        "failure": "Recursive multi-step use compounds error and kernel tuning can be unstable on short series.",
        "sources": ["source_000016", "source_000029"],
        "hyperparameters": ["kernel", "C", "epsilon", "lag_features"],
        "covariates": True,
    },
    {
        "name": "kernel_ridge_lag_regression",
        "category": "kernel",
        "description": "Apply ridge-regularized kernel regression to lagged and optional exogenous features.",
        "assumption": "Future responses vary smoothly under the selected kernel geometry.",
        "failure": "Kernel matrices become costly on large samples and extrapolation beyond observed features is weak.",
        "sources": ["source_000015", "source_000016"],
        "hyperparameters": ["kernel", "ridge_penalty", "lag_features"],
        "covariates": True,
    },
    {
        "name": "neural_network_autoregression",
        "category": "neural",
        "description": "Feed lagged observations and seasonal lags to a shallow multilayer perceptron and recursively forecast.",
        "assumption": "A stable nonlinear lag relationship can be learned from enough repeated patterns.",
        "failure": "Small samples, regime shifts, and recursive error accumulation degrade long-horizon forecasts.",
        "sources": ["source_000001"],
        "hyperparameters": ["lag_order", "hidden_units", "weight_decay"],
    },
    {
        "name": "deepar",
        "category": "neural",
        "description": "Train one autoregressive recurrent network across related series to output a parametric predictive distribution.",
        "assumption": "Related training series share learnable dynamics and the chosen likelihood is suitable.",
        "failure": "Few unrelated series or a misspecified likelihood prevent useful global transfer.",
        "sources": ["source_000017"],
        "hyperparameters": ["context_length", "rnn_layers", "likelihood"],
        "covariates": True,
        "probabilistic": True,
    },
    {
        "name": "nbeats",
        "category": "neural",
        "description": "Stack backward and forward fully connected residual blocks with optional trend and seasonal bases.",
        "assumption": "A large collection of training windows supports learning reusable basis expansions.",
        "failure": "Very small samples or abrupt unseen regimes cause high-variance extrapolation.",
        "sources": ["source_000018"],
        "hyperparameters": ["stack_types", "blocks", "hidden_units"],
    },
    {
        "name": "nhits",
        "category": "neural",
        "description": "Use hierarchical interpolation and multi-rate input pooling to model different forecast frequencies.",
        "assumption": "Forecast structure can be decomposed across multiple temporal resolutions.",
        "failure": "Resolution choices can suppress sharp high-frequency events important to the target.",
        "sources": ["source_000019"],
        "hyperparameters": ["pooling_sizes", "frequency_downsample", "blocks"],
    },
    {
        "name": "temporal_fusion_transformer",
        "category": "neural",
        "description": "Combine recurrent local processing, variable selection, gating, and attention for multi-horizon forecasts with covariates.",
        "assumption": "Known-future and observed covariates contain stable cross-series predictive information.",
        "failure": "Sparse data or unreliable future covariates make the high-capacity architecture overfit.",
        "sources": ["source_000020"],
        "hyperparameters": ["hidden_size", "attention_heads", "dropout"],
        "covariates": True,
        "probabilistic": True,
    },
    {
        "name": "intervention_arima",
        "category": "outlier_handling",
        "description": "Jointly estimate ARIMA dynamics and explicit pulse, level-shift, or temporary-change intervention effects.",
        "assumption": "Outlier timing or intervention shape can be identified separately from recurring dynamics.",
        "failure": "Many overlapping anomalies are confounded with structural breaks and ARIMA parameters.",
        "sources": ["source_000021"],
        "hyperparameters": ["intervention_types", "arima_order"],
    },
    {
        "name": "outlier_adjusted_arima",
        "category": "outlier_handling",
        "description": "Detect additive and innovative outliers, estimate their effects, clean the series, and refit ARIMA.",
        "assumption": "A sparse set of abnormal observations contaminates an otherwise stable ARIMA process.",
        "failure": "Persistent regime changes are incorrectly removed as isolated contamination.",
        "sources": ["source_000021"],
        "hyperparameters": ["outlier_threshold", "outlier_types", "arima_order"],
    },
    {
        "name": "markov_switching_autoregression",
        "category": "regime_switching",
        "description": "Use a latent Markov state to switch autoregressive parameters, level, or variance across regimes.",
        "assumption": "A small set of persistent latent regimes generates the observed dynamics.",
        "failure": "Regimes with few visits are weakly identified and unprecedented states cannot be represented.",
        "sources": ["source_000022"],
        "hyperparameters": ["regime_count", "ar_order", "switching_variance"],
        "probabilistic": True,
    },
    {
        "name": "threshold_autoregression",
        "category": "regime_switching",
        "description": "Switch autoregressive equations when a threshold variable crosses estimated cut points.",
        "assumption": "Regime transitions are driven by observable threshold conditions.",
        "failure": "Smooth transitions or time-varying thresholds make hard partitions unstable.",
        "sources": ["source_000023"],
        "hyperparameters": ["threshold_variable", "thresholds", "ar_orders"],
    },
    {
        "name": "smooth_transition_autoregression",
        "category": "regime_switching",
        "description": "Blend autoregressive regimes continuously with a logistic or exponential transition function.",
        "assumption": "Nonlinear dynamics vary smoothly with an observable transition variable.",
        "failure": "Limited observations near the transition region make slope and threshold estimates unstable.",
        "sources": ["source_000024"],
        "hyperparameters": ["transition_function", "threshold", "smoothness", "ar_order"],
    },
    {
        "name": "bats",
        "category": "seasonal",
        "description": "Combine Box-Cox transformation, ARMA errors, trend, and one seasonal component in state space.",
        "assumption": "Transformed seasonal dynamics and residual autocorrelation remain stable.",
        "failure": "Multiple or rapidly changing seasonalities are not captured by a single seasonal state.",
        "sources": ["source_000025"],
        "hyperparameters": ["boxcox", "arma_errors", "damped_trend", "season_length"],
        "probabilistic": True,
    },
    {
        "name": "tbats",
        "category": "seasonal",
        "description": "Extend BATS with trigonometric states so multiple and non-integer seasonal periods can be modeled.",
        "assumption": "Complex seasonalities can be represented by stable Fourier state components.",
        "failure": "Long histories and many harmonics make fitting expensive and can overfit weak cycles.",
        "sources": ["source_000025"],
        "hyperparameters": ["seasonal_periods", "harmonics", "boxcox", "arma_errors"],
        "probabilistic": True,
    },
    {
        "name": "dynamic_harmonic_regression_arima",
        "category": "seasonal",
        "description": "Regress on Fourier terms for one or more seasonal periods while modeling remaining errors with ARIMA.",
        "assumption": "Seasonal shapes are smooth and repeat while residual autocorrelation follows ARIMA dynamics.",
        "failure": "Changing seasonal timing or event-driven pulses cannot be represented by fixed harmonics.",
        "sources": ["source_000001"],
        "hyperparameters": ["fourier_orders", "seasonal_periods", "arima_order"],
    },
    {
        "name": "mstl_ets",
        "category": "seasonal",
        "description": "Decompose multiple seasonal periods with repeated STL, forecast the adjusted series with ETS, and restore each seasonal component.",
        "assumption": "Several stable seasonal periods coexist and can be separated additively.",
        "failure": "Short histories or interacting seasonal amplitudes make the sequential decomposition unreliable.",
        "sources": ["source_000002", "source_000010"],
        "hyperparameters": ["seasonal_periods", "stl_windows", "ets_model"],
        "probabilistic": True,
    },
    {
        "name": "random_forest_lag_forecast",
        "category": "tree",
        "description": "Train an ensemble of randomized regression trees on lag, rolling, calendar, and optional exogenous features.",
        "assumption": "Historical feature-target relationships recur within the range covered by training data.",
        "failure": "Trees do not extrapolate trends beyond observed target regions and recursive forecasts compound errors.",
        "sources": ["source_000016", "source_000026"],
        "hyperparameters": ["lag_features", "tree_count", "max_depth"],
        "covariates": True,
    },
    {
        "name": "xgboost_lag_forecast",
        "category": "tree",
        "description": "Boost regularized regression trees over lag, rolling, calendar, and exogenous features.",
        "assumption": "Engineered features expose repeatable nonlinear splits predictive of future targets.",
        "failure": "Extrapolation and unseen regimes remain weak even when in-range fit is strong.",
        "sources": ["source_000016", "source_000027"],
        "hyperparameters": ["lag_features", "depth", "learning_rate", "estimators"],
        "covariates": True,
    },
    {
        "name": "lightgbm_lag_forecast",
        "category": "tree",
        "description": "Fit histogram-based leaf-wise gradient-boosted trees to time-series lag and covariate features.",
        "assumption": "Large enough supervised windows support stable nonlinear partitions of engineered features.",
        "failure": "Leaf-wise growth overfits small series and cannot reliably extrapolate outside training targets.",
        "sources": ["source_000016", "source_000028"],
        "hyperparameters": ["lag_features", "num_leaves", "learning_rate", "estimators"],
        "covariates": True,
    },
)


def _jsonl(records: Sequence[Mapping[str, object]]) -> str:
    return "".join(
        json.dumps(record, ensure_ascii=False, sort_keys=True) + "\n"
        for record in records
    )


def _legacy_card(method: Mapping[str, object], index: int) -> MethodCard:
    legacy_id = str(method["method_id"])
    source_ids = SPECIFIC_DEFINITION_SOURCES.get(legacy_id, ("source_000001",))
    return MethodCard.from_payload(
        {
            "method_uid": f"method_seed_{index:04d}",
            "definition_version": 1,
            "canonical_name": legacy_id,
            "aliases": [legacy_id],
            "family": "statistical",
            "category": CATEGORY_BY_LEGACY_ID[legacy_id],
            "description": method["description"],
            "assumptions": method["assumptions"],
            "failure_conditions": method["failure_conditions"],
            "applicability": {
                "minimum_history": 1,
                "frequencies": ["any"],
                "supports_univariate": True,
                "supports_covariates": False,
                "supports_probabilistic_output": (
                    CATEGORY_BY_LEGACY_ID[legacy_id] == "probabilistic"
                ),
            },
            "hyperparameters": [],
            "definition_source_ids": list(source_ids),
            "implementation_source_ids": [],
            "implementation_availability": "unknown",
            "verification_status": "verified",
            "lineage": {
                "operation": "verified_migrated_seed",
                "parent_method_uids": [],
                "legacy_dictionary_id": "statistical_base_methods_v000",
                "legacy_method_id": legacy_id,
            },
            "foundation_metadata": {},
        }
    )


def _extra_statistical_card(spec: Mapping[str, object], index: int) -> MethodCard:
    source_ids = tuple(str(item) for item in spec["sources"])
    implementation_sources = tuple(
        source_id for source_id in source_ids if source_id in {"source_000002", "source_000016"}
    )
    return MethodCard.from_payload(
        {
            "method_uid": f"method_stat_{index:04d}",
            "definition_version": 1,
            "canonical_name": spec["name"],
            "aliases": [],
            "family": "statistical",
            "category": spec["category"],
            "description": spec["description"],
            "assumptions": [spec["assumption"]],
            "failure_conditions": [spec["failure"]],
            "applicability": {
                "minimum_history": 10,
                "frequencies": ["any"],
                "supports_univariate": True,
                "supports_covariates": bool(spec.get("covariates", False)),
                "supports_probabilistic_output": bool(
                    spec.get("probabilistic", False)
                ),
            },
            "hyperparameters": list(spec.get("hyperparameters", [])),
            "definition_source_ids": list(source_ids),
            "implementation_source_ids": list(implementation_sources),
            "implementation_availability": (
                "available" if implementation_sources else "unknown"
            ),
            "verification_status": "verified",
            "lineage": {"operation": "collected", "parent_method_uids": []},
            "foundation_metadata": {},
        }
    )


def write_catalog_manifests(
    legacy_source: str | Path,
    source_destination: str | Path,
    method_destination: str | Path,
) -> tuple[tuple[SourceRecord, ...], tuple[MethodCard, ...]]:
    """Write the reviewed classical batch as deterministic JSONL manifests."""

    legacy_payload = json.loads(Path(legacy_source).read_text(encoding="utf-8"))
    legacy_methods = legacy_payload.get("methods")
    if not isinstance(legacy_methods, list):
        raise ValueError("legacy dictionary must contain a methods list")
    sources = tuple(
        SourceRecord.from_payload(payload)
        for payload in SOURCE_PAYLOADS + ADDITIONAL_STATISTICAL_SOURCE_PAYLOADS
    )
    legacy_cards = tuple(
        _legacy_card(method, index)
        for index, method in enumerate(legacy_methods, start=1)
        if str(method["method_id"]) not in EXCLUDED_LEGACY_IDS
    )
    extra_cards = tuple(
        _extra_statistical_card(spec, index)
        for index, spec in enumerate(EXTRA_STATISTICAL_METHOD_SPECS, start=1)
    )
    methods = legacy_cards + extra_cards
    source_path = Path(source_destination)
    method_path = Path(method_destination)
    source_path.parent.mkdir(parents=True, exist_ok=True)
    method_path.parent.mkdir(parents=True, exist_ok=True)
    source_path.write_text(
        _jsonl([source.to_payload() for source in sources]), encoding="utf-8"
    )
    method_path.write_text(
        _jsonl([method.to_payload() for method in methods]), encoding="utf-8"
    )
    return sources, methods
